language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-staticwebsite' ]; then cd .. && eval "mv $currentfolder generator-staticwebsite" && cd generator-staticwebsite; fi

